---
title: "Publications"
---

My name is cited as Degobi, E. B. or as I was formerly known (Bastos, R. V. S.).

## Books

- **Degobi, E. B.** (2025). Advances in Psychometric Theory and Measurement for Psychological Sciences: With Tutorials in R. https://elliedegb.quarto.pub/psychometrics/

## Journal Articles

1.  Borborema, R. S., de Moraes Ferreira, M., da Silva, A. L. M., **Bastos, R. V. S.**, de Sá, D. G. F., Feldman, G., ... & Batistuzzo, M. C. (2026). Inaction Inertia Effect: Foregoing Opportunities as a Consequence of an Initial Failure to Act–a Replication-Extension Study in the Brazilian Population. *Meta-Psychology*, *10*. https://doi.org/10.15626/MP.2023.3960

2.  Simioni, A., Schafer, J. L., Marchionatti, L. E., Schuster, K., Casella, C. B., Papanikolaou, K., ... & Kotsis, K. (2026). Psychometric properties and local normative references of PSC-17, RCADS-25, CATS-2, SNAP-IV, MCHAT-R/F, and CAST: data from a nationwide sample in Greece. *Journal of Patient-Reported Outcomes*, *62*(10). https://doi.org/10.1186/s41687-026-01032-1

3.  Schoenegger, P., Tuminauskaite, I., Park, P. S., **Bastos, R. V. S.**, & Tetlock, P. E. (2024/2025). Wisdom of the Silicon Crowd: LLM ensemble prediction capabilities rival human crowd accuracy. *Science Advances*, *10*(45), eadp1528. https://doi.org/10.1126/sciadv.adp1528

4.  Blomster Lyshol, J. K., **Bastos, R. V. S.**, Isager, P. M., & Blystad, M. H. (2025). What is empathy for laypeople? – A replication study of Hall, Schwartz, and Duong (2021). *The Journal of Social Psychology*, 1–19. https://doi.org/10.1080/00224545.2025.2482014

5.  Sarfo, J. O., García-Santillán, A., Adusei, H., **Bastos, R. V. S.**, Achido, T. A., Attigah, D. K. (2025). Gender and Age Differences in Behaviours Related to Mathematics Anxiety Across Six Asian Countries. *Journal of Advocacy, Research and Education*, *12*(2), 147-157. https://doi.org/10.13187/jare.2025.2.148

6.  Dahlgren, C. L., Bang, L., & **Degobi, E. B.** (2025). Screening for eating disorders in adolescents: psychometric evaluation of the EDE-QS in a community sample. *BMC Psychology*, *13*(1042). https://doi.org/10.1186/s40359-025-03400-w

7.  de Moraes Ferreira, M., Santiago, M. Y. T., **Bastos, R. V. S.**, Fatori, D., Borborema, R. S., Seda, L., & Batistuzzo, M. C. (2024). Replication: The money illusion effect in a Brazilian sample and meta-analyses. *Journal of Economic Psychology*, *104*, 102744. https://doi.org/10.1016/j.joep.2024.102744

8.  Machado, G. M., Mose, L. B., **Bastos, R. V. S.**, Freitas, C. P. P., Carvalho, L. F. (2024). Violence and bullying in the school context: a multilevel analysis. *Avaliação Psicológica*, *23*, 355-367. https://doi.org/10.15689/ap.2024.2303.10

9.  Valentini, F., Mose, L. B., Franco, G. C., Aire, J. S. O., **Bastos, R. V. S.**, et al. (2024). Inventory of Supporting for Socio-Emotional Skills - Forced-Choice Version. *Paidéia*, *34*, e3408. https://doi.org/10.1590/1982-4327e3408

10. Sarfo, J. O., Ansah, E. W., Apaak, D., & **Bastos, R. V. S.** (2023). Psychometric Properties of a Safety Culture Index among Mental Health Workers in Ghana. *Archives of Psychiatry Research*, *59*(2), 277-284. https://doi.org/10.20471/dec.2023.59.02.11

11. Schönegger, P., Maier, M., & **Bastos, R. V. S.** (2023). Introduction and validation of the Short Antinatalism Scale (S-ANS). *Psychological Test Adaptation and Development*, *4*(1), 28-40. https://doi.org/10.1027/2698-1866/a000036

12. Aquino, S. D., Marot, T. A., Bastos, R. V. S., & Natividade, J. C. (2023). Validity evidence of the Humor Styles Questionnaire in Brazil. *Avaliação Psicológica*, *22*(2), 174-184. https://doi.org/10.15689/ap.2023.2202.21873.07

13. Franco, V. R., Wiberg, M., & **Bastos, R. V. S.** (2023). Nonparametric Item Response Models. *Psico-USF*, 28, 685-696. https://doi.org/10.1590/1413-82712023280403

14. Franco, V. R., Laros, J. A., Wiberg, M., & **Bastos, R. V. S.** (2022). How to think straight about psychometrics. *Trends in Psychology*, 1-21. https://doi.org/10.1007/s43076-022-00183-6

15. Franco, V. R., Laros, J. A., & **Bastos, R. V. S.** (2022). Mokken scale analysis foundations. *Paidéia*, *32*. https://doi.org/10.1590/1982-4327e3223

16. de Carvalho, N. M., **Bastos, R. V. S.**, & Natividade, J. C. (2022). Implicit depressive trait measurement. *Trends in Psychology*, 1-26. https://doi.org/10.1007/s43076-022-00145-y

17. Lopes, K. F., Bahia, V. S., Natividade, J. C., **Bastos, R. V. S.**, et al. (2022). Personality changes in Alzheimer’s disease. *Dementia & Neuropsychologia*, *16*, 187-193. https://doi.org/10.1590/1980-5764-DN-2021-0029

18. Sarfo, J. O., García-Santillán, A., Ansah, E. W., **Bastos, R. V. S.**, et al. (2022). Anxiety Towards Mathematics Scale validation. *European Journal of Contemporary Education*, *11*(2), 504-514. https://doi.org/10.13187/ejced.2022.2.504

19. dos Santos, G. G. B., Soares, A. B., & **Bastos, R. V. S.** (2021). Social skills training and school climate. *Psychology: Theory and Practice*, *23*(2), 1-22. https://doi.org/10.5935/1980-6906/ePTPPE13553

20. Natividade, J. C., Londero-Santos, A., Novaes, F. C., Carvalho, N. M. D., **Bastos, R. V. S.**, & Marot, T. A. (2021). Theory of planned behavior and COVID-19 isolation. *Revista Psicologia e Saúde*, *13*(4), 199-213. https://doi.org/10.20435/pssa.v13i4.1369

## Book Chapters

- Valentini, F., & **Bastos, R. V. S.** (2025). Halo effect: consequences and techniques for assessment and control. In M. P. P. da Silva, & E. M. Peixoto (Orgs.), Response biases in psychological testing and assessment (pp 131-146). Hogrefe.

- Mose, L. B., Lessa, J. P. A., Souza, L. S., & **Bastos, R. V. S.** (2025). Response biases in the assessment of personality traits. In M. P. P. da Silva, & E. M. Peixoto (Orgs.), Response biases in psychological testing and assessment (pp 299-324). Hogrefe.
